language: node_js
node_js:
  - lts/*
script:
  - npm test
after_success:
  - npm install -g zapier-platform-cli
notifications:
  email: false
deploy:
  provider: script
  script:
    - yarn install --silent
    - bash deploy.sh
  on:
    branch: develop
env:
  global:
  - secure: SDRurd2QmMsn3YEwejnXiHf114ClI+jbyr3f8yrJ7rLxrXXWfPPUjKfl2eqKI6p3NIlg/8yplod0azrHu4LSKkX8Sk5hpANxW60arjijNyvSPdEZ7jFU8fkdRUVIFrem96Zj2tVlFxdIi21z4pqnYeCtmd5CuwmrgLgngTRX4r1IAUz93sIVRMlln21LoFy1G9m6ZCd3PhIsLvFFpFjPmmsTJeAhEywGzQg8VPIYaA+VJu6KYzA7cMZebReP3DQvd4v3zGc4+xPbKOGQ1adHtcpz/th2/SF5bOKn8cZX5j8gfDT/7Sa6s1PFPYdhdQdALQdSGVxZ1kfpqVGyACWwf8XHRAPYKhrmx2BUwb8abKAAQRHtzcokFEzmZ9uldXEhJXwwOtXrlf2Yc4AuUCwFxFZ4eAOq6otJrCVE0i5rl0/8dFH5VPe+g9P4XcFe0NQvizRWWWX/q+V/gFQa1ZLYX0sAFQtT6DaADOhOKyj9dChr9oN5WPD2V6pAXtk6+M9orKRJ95wnFTKAErpJefm91FGlEyAGOdtowI4hKUCar+9NMKOwt8IhsC8rVWOmdmYpCqK0aPneW/l8/c88s/E6ZC8r1DBqz232jzxjt5uj9jkMwvLdL4pE9nB4s3d7OPhwNguJXNSz6z6cW14V9UsDyIssGfWr+mO6iuQ25g86CXU=
  - secure: SQh1JtXomv5kX/vYuQgtc2vYX5BR5ficpyDfQ/iR3hroPhHCqfrGgrTJMTGE2kOy4Uu8CEDkAeOGJho/337dYC/gBwwHezCLtYSKuY378owNMUGhwNfjoqgiVRuu78uhB55rT6h+/dRDd1reyGC7LAtoATXoFhGu3pv8l6obGNcti1Efe3axaZ5JH/j0inN4+/Oz9rlqvuCnq4sLz8YH35fQxpKk++S1jNChCCZrnvkuFJePmEkjbIzgqzoY/HqGN8rw0+tM2rWEFopgGwXu2YBKGtXvf5EhWr9buW7pZrmJw8EBXywDw1gE9S7icC/+qsiVnRWIeJabyys69Xp4JL+Y6rotlH/ISzEHPa82jsFWM7jZ1unPVfMUYlgJv3Hw+W02ZJBDh0Dnlc3IOblWv1eLPo0eGpKn1otdjANDOE4NC7z7R/ChM3/HoNXNwRTGH0MBYnwblqfac1/eaTe2CUwn3zySPOdYt4S5oKPZP+Q93FA1TDqqC7Yh6C5d4Fvsb+/8U5gJxHqclgJ5Pp7SUfCbyAQoq9CSVxWF5b4aDS9CDjwKba2sjl76qSw2T/RYB6JCM2vbyvJKTpGmLNcSEyDUzYMBdosd2enZyovNue7xa1c740CeQAHbcKsDHgZcF9/LGnclljrUYkIMOqYxh51d1n2L35koyKos1aihHpM=
